services:
  
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - blog-network
    
    
  backend:
    build : ./server
    ports:
    - "3000:3000"
    networks:
     - blog-network

networks:
  blog-network:
    driver: bridge
